apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: royeis/streamlit:label
        imagePullPolicy: Always
        env:
        - name: "V3IO_ACCESS_KEY"
          value: <ACCESS_KEY>
        ports:
        - containerPort: 8501
        command: ["streamlit", "run", "/User/demos/demos/realtime-face-recognition/streamlit/dashboard.py" ]
        args: []
        volumeMounts:
        - mountPath: User
          name: fs
      volumes:
      - flexVolume:
          driver: v3io/fuse
          options:
            accessKey: <ACCESS_KEY>
            container: users
            subPath: /iguazio
        name: fs
---
kind: Service
apiVersion: v1
metadata:
  name: streamlit
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    nodePort: 30090
    port: 8501
    targetPort: 8501
